baseURL = "https://inkan.link/"
title = "Inkan.link"

languageCode = "fr-fr"
DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false # must stay that way for image in posts. 
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true
pagination.pagerSize = 12
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

# Performance optimizations
disableLiveReload = false
timeout = "30s"

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.getcsv]  
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.getresource]
    dir = ":cacheDir/:project"
    maxAge = "10m"
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "1440m"
  [caches.assets]
    dir = ":resourceDir/_gen"  
    maxAge = "1440m"
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "1440m"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false

[params]
author = "Inkan.link"
authorimage = "../assets/images/global/SquircleLogoInkan.webp"
github = "https://github.com/inkan-tech"
facebook = "https://facebook.com/"
og_image = "/images/InkanLogo.webp"
sitename = "Inkan.link"
twitter = "@SealfieApp"
twitter_site = "@SealfieApp"
twitter_creator = "@SealfieApp"
description = "Inkan.link have confidence in who you are communicating with"
[params.navigation]
      about = 'About'
      team = 'Team'      
      contacts = 'Contacts'
      legal = 'Legal'
[imaging]
  resampleFilter = "Lanczos"
  quality = 85
  anchor = "Smart"
  [imaging.exif]
    includeFields = ""
    excludeFields = "GPS|Exif|IPTC|IFD0|IFD1"
    disableDate = false
    disableLatLong = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
  autoHeadingID = true
  autoHeadingIDType = "github"
[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

[taxonomies]
category = "Categories"
tag = "Tags"
[permalinks]
    post = "/blog/:title/"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.instagram]
disable = true
simple = false
[privacy.twitter]
enableDNT = false
simple = false
[privacy.vimeo]
disable = true
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

copyright = 'Inkan.link reserved'
[languages]
  [languages.en]
    title = 'Inkan.link'
    weight = 1
    # [languages.en.params]
    #   linkedin = 'https://linkedin.com/whoever'
  [languages.fr]
    title =  'Inkan.link'
    weight = 1
    [languages.fr.params]
      # linkedin = 'https://linkedin.com/fr/whoever'
        description = "Inkan.link être sûr de son interlocuteur " 
      [languages.fr.params.navigation]
        about = 'A propos'
        team = "L'équipe"      
        contacts = 'Contacts'
        legal = 'Mentions légales'


[module]
  [module.hugoVersion]
    extended = true
    min = "0.130.0"
    max = "0.155.1"
