baseURL = "https://inkan-tech.github.io/https.inkan.link/"
title = "Inkan.link"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = "Inkan.link SAS"
authorimage = "../assets/images/global/SquircleLogoInkan.webp"
github = "https://github.com/inkan-tech"
facebook = "https://facebook.com/nusserstudios"
og_image = "/images/tailbliss-cover.png"
sitename = "Inkan.link"
twitter = "@inkan.link"
description = "Inkan.link prevents identity theft consequences"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.instagram]
disable = true
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = true
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.105.0"
    max = "0.105.0"
