baseURL = "https://inkan.link/"
title = "Inkan.link"

languageCode = "fr-fr"
DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false # must stay that way for image in posts. 
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = "Inkan.link"
authorimage = "../assets/images/global/SquircleLogoInkan.webp"
github = "https://github.com/inkan-tech"
facebook = "https://facebook.com/"
og_image = "/images/InkanLogo.webp"
sitename = "Inkan.link"
twitter = "@inkan.link"
description = "Inkan.link have confidence in who you are communicating with"
[params.navigation]
      about = 'About'
      team = 'Team'      
      contacts = 'Contacts'
      legal = 'Legal'
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"
[permalinks]
    post = "/blog/:title/"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = true
respectDoNotTrack = true
useSessionStorage = false
[privacy.instagram]
disable = true
simple = false
[privacy.twitter]
disable = true
enableDNT = false
simple = false
[privacy.vimeo]
disable = true
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

copyright = 'Inkan.link reserved'
[languages]
  [languages.en]
    title = 'Inkan.link'
    weight = 1
    # [languages.en.params]
    #   linkedin = 'https://linkedin.com/whoever'
  [languages.fr]
    title =  'Inkan.link'
    weight = 1
    [languages.fr.params]
      # linkedin = 'https://linkedin.com/fr/whoever'
        description = "Inkan.link être sûr de son interlocuteur " 
      [languages.fr.params.navigation]
        about = 'A propos'
        team = "L'équipe"      
        contacts = 'Contacts'
        legal = 'Mentions légales'


[module]
  [module.hugoVersion]
    extended = true
    min = "0.107.0"
    max = "0.109.0"
